# Usage: bash examples/offline_rl/policy_optimization/cfg_rl/run_cfg_rl.sh cfg_rl_openpi

defaults:
  - model/pi0_5@actor.model
  - hybrid_engines/fsdp@actor.fsdp_config
  - _self_
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:REPO_PATH}/examples/offline_rl/config/

cluster:
  num_nodes: 1
  component_placement:
    actor,env,rollout: all

runner:
  task_type: sft
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "cfg_sft"
    logger_backends: ["tensorboard"]

  max_epochs: 30000
  max_steps: -1
  val_check_interval: -1
  save_interval: 3000

data:
  num_workers: 8
  advantage_tag: null
  balance_dataset_weights: true
  seed: 42

  train_data_paths:
    - dataset_path: "/path/to/sft_dataset"
      type: "sft"
      weight: 1.0

algorithm:
  adv_type: gae

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 32
  global_batch_size: 512
  seed: 0

  model:
    precision: null
    model_path: "/path/to/pi05_base_pytorch"
    model_type: "cfg_model"
    add_value_head: False
    openpi:
      config_name: "pi05_libero"
      cfgrl_guidance_scale: 1.0
      unconditional_prob: 0.1
      train_expert_only: False
      guidance_type: "positive"
      positive_only_conditional: true

  optim:
    lr: 1.0e-5
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-8
    weight_decay: 1.0e-10
    clip_grad: 1.0
    lr_scheduler: "cosine"
    lr_warmup_steps: 5000
    total_training_steps: 30000
    min_lr: 0.0

  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "no_shard"
    use_orig_params: False
    gradient_checkpointing: True
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: False

critic:
  use_critic_model: False
