env_type: "diffusion"
seed: 42
total_num_envs: 24
group_size: 3
auto_reset: False
ignore_terminations: False
max_episode_steps: 1
max_steps_per_rollout_epoch: 1
is_eval: False

video_cfg:
  save_video: False
  info_on_video: False
  video_base_dir: ${runner.logger.log_path}/video/ocr_reward

dataset:
  type: "visual.ocr_dataset"
  # Download from https://github.com/NVlabs/DiffusionNFT/tree/main/dataset/ocr.
  # The directory should contain train.txt and test.txt.
  path: /path/to/dataset/ocr
  split: "train"

reward:
  type: "single"
  model: "visual.ocr"
  key: "avg"
  use_gpu: False
  lang: "en"
